version: '3'
services:
  postgres_nodes:
    container_name: postgres_nodes
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
    ports:
      - 5432:5432
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
