spring:
  application:
    name: webSite

  datasource:
    url: jdbc:postgresql://localhost:5436/root
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080