INSERT INTO nodes (name, type, parent_id, url) VALUES ('Root Node', 'FOLDER', NULL, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 1', 'FILE', 1, 'http://example.com/file1');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 2', 'FILE', 1, 'http://example.com/file2');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 3', 'FOLDER', 1, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 1', 'LINK', 4, 'https://www.youtube.com/embed/00-hcWc7_fA?si=SrDapjG61P8oDOBr');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 2', 'FILE', 4, 'http://example.com/file4');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Root Node 2', 'FOLDER', NULL, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 4', 'FOLDER', 7, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 5', 'LINK', 7, 'https://www.youtube.com/embed/_zaehrkPuuI?si=4tSwrCD7keoDRY6t');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 6', 'FILE', 8, 'http://example.com/file6');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Root Node 3', 'FOLDER', NULL, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 7', 'FILE', 10, 'http://example.com/file7');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 8', 'FILE', 10, 'http://example.com/file8');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 9', 'FOLDER', 10, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 3', 'FILE', 13, 'http://example.com/file9');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 4', 'FILE', 13, 'http://example.com/file10');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Root Node 4', 'FOLDER', NULL, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 10', 'FILE', 16, 'http://example.com/file11');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 11', 'FILE', 16, 'http://example.com/file12');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Child Node 12', 'FOLDER', 16, NULL);
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 5', 'FILE', 19, 'http://example.com/file13');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('Grandchild Node 6', 'FILE', 19, 'http://example.com/file14');
INSERT INTO nodes (name, type, parent_id, url) VALUES ('dddd', 'FILE', 4, 'https://youtu.be/gaxQoucrWrk?si=m8KKeBvqyXi2DbB8');